#!/usr/bin/env python3
"""Fetch one cached-or-live alphaXiv overview on a separate library connection."""
import json
import socket
import sys


def library_call(socket_path, method, params):
    with socket.socket(socket.AF_UNIX) as connection:
        connection.settimeout(3)
        connection.connect(socket_path)
        connection.sendall((json.dumps(dict(v=1, id=1, method=method, params=params)) + '\n').encode())
        response = json.loads(connection.makefile().readline())
    if 'error' in response:
        raise ValueError(response['error']['message'])
    return response['result']

if __name__ == '__main__':
    try:
        print(json.dumps(library_call(sys.argv[1], 'get_alphaxiv_overview', {'id': sys.argv[2]})), flush=True)
    except Exception as error:
        print(json.dumps({'error': str(error)}), flush=True)
        sys.exit(1)
